### ISSUE TITLE
Train ICDAR2015 data set: TypeError: unsupported operand type(s) for -: 'NoneType' and 'float' 

### ISSUE THREAD

**Issue by XuLiangFRDC** [argman/EAST#102]
@argman I try to train the model by icdar2015 Incidental Scene Text data set for Text Localization (1000 image samples). 

**The training script is as follows:**
     python multigpu_train.py --gpu_list=2 --input_size=512 --batch_size_per_gpu=20 --checkpoint_path=./tmp/model_east_icdar2015_trn_set_resnet_v1_50_rbox/ --text_scale=512 --training_data_path=/home/database/icdar2015_ch4_training_images_with_gt_rn/ --geometry=RBOX --learning_rate=0.0001 --num_readers=20 --pretrained_model_path=./tmp/resnet_v1_50.ckpt 

I have changed the gt text file of icdar2015's filename to img_*.txt instead of gt_img_*.txt as your readme suggests. Also,  as you mentioned some extra characters should be removed from the file, I guess that I need to remove the comma symbol from the file. I think it is OK for icdar2015's gt text file.

My OS is CentOS 7. I use one GPU card, which is Nvidia P40. 

The training process can go on, but after several steps some error messages will print and repeat as follows:

Shape of h_0 (?, ?, ?, 2048), g_0 (?, ?, ?, 2048)
Shape of h_1 (?, ?, ?, 128), g_1 (?, ?, ?, 128)
Shape of h_2 (?, ?, ?, 64), g_2 (?, ?, ?, 64)
Shape of h_3 (?, ?, ?, 32), g_3 (?, ?, ?, 32)
_**Traceback (most recent call last):
  File "/home/xuliang/EAST_Github_180129/EAST/icdar.py", line 658, in generator
    score_map, geo_map, training_mask = generate_rbox((new_h, new_w), text_polys, text_tags)
  File "/home/xuliang/EAST_Github_180129/EAST/icdar.py", line 520, in generate_rbox
    if point_dist_to_line(p1, new_p2, p0) > point_dist_to_line(p1, new_p2, p3):
  File "/home/xuliang/EAST_Github_180129/EAST/icdar.py", line 248, in point_dist_to_line
    return np.linalg.norm(np.cross(p2 - p1, p1 - p3)) / np.linalg.norm(p2 - p1)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
Traceback (most recent call last):
  File "/home/xuliang/EAST_Github_180129/EAST/icdar.py", line 658, in generator
    score_map, geo_map, training_mask = generate_rbox((new_h, new_w), text_polys, text_tags)
  File "/home/xuliang/EAST_Github_180129/EAST/icdar.py", line 520, in generate_rbox
    if point_dist_to_line(p1, new_p2, p0) > point_dist_to_line(p1, new_p2, p3):
  File "/home/xuliang/EAST_Github_180129/EAST/icdar.py", line 248, in point_dist_to_line
    return np.linalg.norm(np.cross(p2 - p1, p1 - p3)) / np.linalg.norm(p2 - p1)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
/home/xuliang/EAST_Github_180129/EAST/icdar.py:248: RuntimeWarning: invalid value encountered in float_scalars
  return np.linalg.norm(np.cross(p2 - p1, p1 - p3)) / np.linalg.norm(p2 - p1)
Traceback (most recent call last):
  File "/home/xuliang/EAST_Github_180129/EAST/icdar.py", line 658, in generator
    score_map, geo_map, training_mask = generate_rbox((new_h, new_w), text_polys, text_tags)
  File "/home/xuliang/EAST_Github_180129/EAST/icdar.py", line 520, in generate_rbox
    if point_dist_to_line(p1, new_p2, p0) > point_dist_to_line(p1, new_p2, p3):
  File "/home/xuliang/EAST_Github_180129/EAST/icdar.py", line 248, in point_dist_to_line
    return np.linalg.norm(np.cross(p2 - p1, p1 - p3)) / np.linalg.norm(p2 - p1)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
/home/xuliang/EAST_Github_180129/EAST/icdar.py:248: RuntimeWarning: invalid value encountered in float_scalars
  return np.linalg.norm(np.cross(p2 - p1, p1 - p3)) / np.linalg.norm(p2 - p1)
/home/xuliang/EAST_Github_180129/EAST/icdar.py:248: RuntimeWarning: invalid value encountered in float_scalars
  return np.linalg.norm(np.cross(p2 - p1, p1 - p3)) / np.linalg.norm(p2 - p1)**_
Step 000000, model loss 0.0139, total loss 0.0463, 0.67 seconds/step, 30.01 examples/second
Step 000010, model loss 0.0175, total loss 0.0496, 3.54 seconds/step, 5.66 examples/second
Step 000020, model loss 0.0247, total loss 0.0566, 1.45 seconds/step, 13.76 examples/second  

Step 000430, model loss 0.0149, total loss 0.0389, 1.52 seconds/step, 13.15 examples/second
Step 000440, model loss 0.0112, total loss 0.0351_/home/xuliang/EAST_Github_180129/EAST/icdar.py:248: RuntimeWarning: invalid value encountered in float_scalars
  return np.linalg.norm(np.cross(p2 - p1, p1 - p3)) / np.linalg.norm(p2 - p1)
/home/xuliang/EAST_Github_180129/EAST/icdar.py:248: RuntimeWarning: invalid value encountered in float_scalars
  return np.linalg.norm(np.cross(p2 - p1, p1 - p3)) / np.linalg.norm(p2 - p1)
/home/xuliang/EAST_Github_180129/EAST/icdar.py:248: RuntimeWarning: invalid value encountered in float_scalars
  return np.linalg.norm(np.cross(p2 - p1, p1 - p3)) / np.linalg.norm(p2 - p1)
/home/xuliang/EAST_Github_180129/EAST/icdar.py:248: RuntimeWarning: invalid value encountered in float_scalars
  return np.linalg.norm(np.cross(p2 - p1, p1 - p3)) / np.linalg.norm(p2 - p1)
/home/xuliang/EAST_Github_180129/EAST/icdar.py:248: RuntimeWarning: invalid value encountered in float_scalars
  return np.linalg.norm(np.cross(p2 - p1, p1 - p3)) / np.linalg.norm(p2 - p1)_
, 1.41 seconds/step, 14.21 examples/second
Step 000450, model loss 0.0119, total loss 0.0356, 1.30 seconds/step, 15.43 examples/second
Step 000460, model loss 0.0131, total loss 0.0365, 1.35 seconds/step, 14.79 examples/second

Step 001310, model loss 0.0119, total loss 0.0250, 1.41 seconds/step, 14.17 examples/second
Step 001320, model loss 0.0120, total loss 0.0250, 1.22 seconds/step, 16.35 examples/second
Step 001330, model loss 0.0108, total loss 0.0237, 1.3_**Traceback (most recent call last):
  File "/home/xuliang/EAST_Github_180129/EAST/icdar.py", line 658, in generator
    score_map, geo_map, training_mask = generate_rbox((new_h, new_w), text_polys, text_tags)
  File "/home/xuliang/EAST_Github_180129/EAST/icdar.py", line 520, in generate_rbox
    if point_dist_to_line(p1, new_p2, p0) > point_dist_to_line(p1, new_p2, p3):
  File "/home/xuliang/EAST_Github_180129/EAST/icdar.py", line 248, in point_dist_to_line
    return np.linalg.norm(np.cross(p2 - p1, p1 - p3)) / np.linalg.norm(p2 - p1)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
Traceback (most recent call last):
  File "/home/xuliang/EAST_Github_180129/EAST/icdar.py", line 658, in generator
    score_map, geo_map, training_mask = generate_rbox((new_h, new_w), text_polys, text_tags)
  File "/home/xuliang/EAST_Github_180129/EAST/icdar.py", line 520, in generate_rbox
    if point_dist_to_line(p1, new_p2, p0) > point_dist_to_line(p1, new_p2, p3):
  File "/home/xuliang/EAST_Github_180129/EAST/icdar.py", line 248, in point_dist_to_line
    return np.linalg.norm(np.cross(p2 - p1, p1 - p3)) / np.linalg.norm(p2 - p1)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'**_
2 seconds/step, 15.12 examples/second
Step 001340, model loss 0.0110, total loss 0.0238, 1.45 seconds/step, 13.77 examples/second
Step 001350, model loss 0.0116, total loss 0.0244, 1.33 seconds/step, 15.06 examples/second

Step 001760, model loss 0.0103, total loss 0.0206, 1.31 seconds/step, 15.24 examples/second
Step 001770, model loss 0.0105, total loss 0.0207, 1.28 seconds/step, 15.63 examples/second
_**Step 00178Traceback (most recent call last):
  File "/home/xuliang/EAST_Github_180129/EAST/icdar.py", line 658, in generator
    score_map, geo_map, training_mask = generate_rbox((new_h, new_w), text_polys, text_tags)
  File "/home/xuliang/EAST_Github_180129/EAST/icdar.py", line 520, in generate_rbox
    if point_dist_to_line(p1, new_p2, p0) > point_dist_to_line(p1, new_p2, p3):
  File "/home/xuliang/EAST_Github_180129/EAST/icdar.py", line 248, in point_dist_to_line
    return np.linalg.norm(np.cross(p2 - p1, p1 - p3)) / np.linalg.norm(p2 - p1)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
Traceback (most recent call last):
  File "/home/xuliang/EAST_Github_180129/EAST/icdar.py", line 658, in generator
    score_map, geo_map, training_mask = generate_rbox((new_h, new_w), text_polys, text_tags)
  File "/home/xuliang/EAST_Github_180129/EAST/icdar.py", line 520, in generate_rbox
    if point_dist_to_line(p1, new_p2, p0) > point_dist_to_line(p1, new_p2, p3):
  File "/home/xuliang/EAST_Github_180129/EAST/icdar.py", line 248, in point_dist_to_line
    return np.linalg.norm(np.cross(p2 - p1, p1 - p3)) / np.linalg.norm(p2 - p1)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
Traceback (most recent call last):
  File "/home/xuliang/EAST_Github_180129/EAST/icdar.py", line 658, in generator
    score_map, geo_map, training_mask = generate_rbox((new_h, new_w), text_polys, text_tags)
  File "/home/xuliang/EAST_Github_180129/EAST/icdar.py", line 520, in generate_rbox
    if point_dist_to_line(p1, new_p2, p0) > point_dist_to_line(p1, new_p2, p3):
  File "/home/xuliang/EAST_Github_180129/EAST/icdar.py", line 248, in point_dist_to_line
    return np.linalg.norm(np.cross(p2 - p1, p1 - p3)) / np.linalg.norm(p2 - p1)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'**_
0, model loss 0.0103, total loss 0.0204, 1.42 seconds/step, 14.04 examples/second
Step 001790, model loss 0.0124, total loss 0.0225, 1.34 seconds/step, 14.91 examples/second
Step 001800, model loss 0.0112, total loss 0.0212, 1.33 seconds/step, 15.09 examples/second

Step 099780, model loss 0.0017, total loss 0.0028, 1.23 seconds/step, 16.30 examples/second
Step 099790, model loss 0.0013, total loss 0.0025, 1.23 seconds/step,_**Traceback (most recent call last):
  File "/home/xuliang/EAST_Github_180129/EAST/icdar.py", line 658, in generator
    score_map, geo_map, training_mask = generate_rbox((new_h, new_w), text_polys, text_tags)
  File "/home/xuliang/EAST_Github_180129/EAST/icdar.py", line 520, in generate_rbox
    if point_dist_to_line(p1, new_p2, p0) > point_dist_to_line(p1, new_p2, p3):
  File "/home/xuliang/EAST_Github_180129/EAST/icdar.py", line 248, in point_dist_to_line
    return np.linalg.norm(np.cross(p2 - p1, p1 - p3)) / np.linalg.norm(p2 - p1)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
Traceback (most recent call last):
  File "/home/xuliang/EAST_Github_180129/EAST/icdar.py", line 658, in generator
    score_map, geo_map, training_mask = generate_rbox((new_h, new_w), text_polys, text_tags)
  File "/home/xuliang/EAST_Github_180129/EAST/icdar.py", line 520, in generate_rbox
    if point_dist_to_line(p1, new_p2, p0) > point_dist_to_line(p1, new_p2, p3):
  File "/home/xuliang/EAST_Github_180129/EAST/icdar.py", line 248, in point_dist_to_line
    return np.linalg.norm(np.cross(p2 - p1, p1 - p3)) / np.linalg.norm(p2 - p1)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
Traceback (most recent call last):
  File "/home/xuliang/EAST_Github_180129/EAST/icdar.py", line 658, in generator
    score_map, geo_map, training_mask = generate_rbox((new_h, new_w), text_polys, text_tags)
  File "/home/xuliang/EAST_Github_180129/EAST/icdar.py", line 520, in generate_rbox
    if point_dist_to_line(p1, new_p2, p0) > point_dist_to_line(p1, new_p2, p3):
  File "/home/xuliang/EAST_Github_180129/EAST/icdar.py", line 248, in point_dist_to_line
    return np.linalg.norm(np.cross(p2 - p1, p1 - p3)) / np.linalg.norm(p2 - p1)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'**_
 16.29 examples/second
Step 099800, model loss 0.0015, total loss 0.0026, 1.23 seconds/step, 16.29 examples/second
Step 099810, model loss 0.0014, total loss 0.0026, 1.34 seconds/step, 14.91 examples/second

You kindly provide the Models trained on ICDAR 2013 (training set) + ICDAR 2015 (training set). I download and try to evaluate by them. The performance is very good. Thanks for your kind sharing and open source.  Do you meet such error messages during your training? How to solve them? Look forward to your kind reply.

**Comment by ZhangGongjie** [comment]
@XuLiangFRDC 
Hi. I have encountered the same problem. May I ask, does this error have any negative effect on the training process? If any, how to solve?

Thank you very much.   :)

**Comment by UpCoder** [comment]
Me too, Why did the error occur? Because the divided number is zero?

**Comment by AlwaysTrying** [comment]
@argman @zxytim  thanks for the work, could you please provide an explanation for this?
I also get
Corrupt JPEG data: premature end of data segment
what does that mean ?

**Comment by AlwaysTrying** [comment]
hello , any one knows the meaning of this:
Corrupt JPEG data: premature end of data segment
 please !!

**Comment by Antonio-hi** [comment]
> there are some wrong polygons in train label on icdar2015, you should add some code in check_and_validate_polys as follows：
> def check_and_validate_polys(polys, tags, xxx_todo_changeme):
> '''
> check so that the text poly is in the same direction,
> and also filter some invalid polygons
> :param polys:
> :param tags:
> :return:
> '''
> (h, w) = xxx_todo_changeme
> if polys.shape[0] == 0:
> return polys
> polys[:, :, 0] = np.clip(polys[:, :, 0], 0, w-1)
> polys[:, :, 1] = np.clip(polys[:, :, 1], 0, h-1)
> 
> ```
> validated_polys = []
> validated_tags = []
> for poly, tag in zip(polys, tags):
>     p_area = polygon_area(poly)
>     if is_polygon(poly) is False:
>         print("not a polygon: ", poly)
>         continue
>     if abs(p_area) < 1:
>         # print poly
>         print('invalid poly')
>         continue
>     if p_area > 0:
>         print('poly in wrong direction')
>         poly = poly[(0, 3, 2, 1), :]
>     validated_polys.append(poly)
>     validated_tags.append(tag)
> return np.array(validated_polys), np.array(validated_tags) 
> ```



> there are some wrong polygons in train label on icdar2015, you should add some code in check_and_validate_polys as follows：
> def check_and_validate_polys(polys, tags, xxx_todo_changeme):
> '''
> check so that the text poly is in the same direction,
> and also filter some invalid polygons
> :param polys:
> :param tags:
> :return:
> '''
> (h, w) = xxx_todo_changeme
> if polys.shape[0] == 0:
> return polys
> polys[:, :, 0] = np.clip(polys[:, :, 0], 0, w-1)
> polys[:, :, 1] = np.clip(polys[:, :, 1], 0, h-1)
> 
> ```
> validated_polys = []
> validated_tags = []
> for poly, tag in zip(polys, tags):
>     p_area = polygon_area(poly)
>     if is_polygon(poly) is False:
>         print("not a polygon: ", poly)
>         continue
>     if abs(p_area) < 1:
>         # print poly
>         print('invalid poly')
>         continue
>     if p_area > 0:
>         print('poly in wrong direction')
>         poly = poly[(0, 3, 2, 1), :]
>     validated_polys.append(poly)
>     validated_tags.append(tag)
> return np.array(validated_polys), np.array(validated_tags) 
> ```

How is the is_polygon function written?

**Comment by Antonio-hi** [comment]
> there are some wrong polygons in train label on icdar2015, you should add some code in check_and_validate_polys as follows：
> def check_and_validate_polys(polys, tags, xxx_todo_changeme):
> '''
> check so that the text poly is in the same direction,
> and also filter some invalid polygons
> :param polys:
> :param tags:
> :return:
> '''
> (h, w) = xxx_todo_changeme
> if polys.shape[0] == 0:
> return polys
> polys[:, :, 0] = np.clip(polys[:, :, 0], 0, w-1)
> polys[:, :, 1] = np.clip(polys[:, :, 1], 0, h-1)
> 
> ```
> validated_polys = []
> validated_tags = []
> for poly, tag in zip(polys, tags):
>     p_area = polygon_area(poly)
>     if is_polygon(poly) is False:
>         print("not a polygon: ", poly)
>         continue
>     if abs(p_area) < 1:
>         # print poly
>         print('invalid poly')
>         continue
>     if p_area > 0:
>         print('poly in wrong direction')
>         poly = poly[(0, 3, 2, 1), :]
>     validated_polys.append(poly)
>     validated_tags.append(tag)
> return np.array(validated_polys), np.array(validated_tags) 
> ```

How is the is_polygon function written? @zuokai

**Comment by zuokai** [comment]
> > there are some wrong polygons in train label on icdar2015, you should add some code in check_and_validate_polys as follows：
> > def check_and_validate_polys(polys, tags, xxx_todo_changeme):
> > '''
> > check so that the text poly is in the same direction,
> > and also filter some invalid polygons
> > :param polys:
> > :param tags:
> > :return:
> > '''
> > (h, w) = xxx_todo_changeme
> > if polys.shape[0] == 0:
> > return polys
> > polys[:, :, 0] = np.clip(polys[:, :, 0], 0, w-1)
> > polys[:, :, 1] = np.clip(polys[:, :, 1], 0, h-1)
> > ```
> > validated_polys = []
> > validated_tags = []
> > for poly, tag in zip(polys, tags):
> >     p_area = polygon_area(poly)
> >     if is_polygon(poly) is False:
> >         print("not a polygon: ", poly)
> >         continue
> >     if abs(p_area) < 1:
> >         # print poly
> >         print('invalid poly')
> >         continue
> >     if p_area > 0:
> >         print('poly in wrong direction')
> >         poly = poly[(0, 3, 2, 1), :]
> >     validated_polys.append(poly)
> >     validated_tags.append(tag)
> > return np.array(validated_polys), np.array(validated_tags) 
> > ```
> 
> How is the is_polygon function written? @zuokai

#新增判断是否是polygon逻辑
def is_polygon(poly):
    for i in range(3):
        p0 = poly[i]
        p1 = poly[(i + 1) % 4]
        p2 = poly[(i + 2) % 4]
        #判断是否有两个点重叠
        if p0[0] == p1[0] and p1[1] == p0[1]:
            return False
        if p0[0] == p2[0] and p2[1] == p0[1]:
            return False
        if p1[0] == p2[0] and p1[1] == p2[1]:
            return False
        #判断是否有3个点在一条直线上
        if p0[0] == p1[0]:
            if p1[0] == p2[0]:
                return False
        else:
            if p1[0] != p2[0]:
                k1 = (p1[1] - p0[1]) / (p1[0] - p0[0])
                k2 = (p2[1] - p1[1]) / (p2[0] - p1[0])
                if abs(k1 - k2) < 1e-6:
                    return False
            else:
                if p1[1] == p2[1]:
                    return False
    #还需要判断两线段（p0p1与p2p3）是否有交点，因label中不存在这种错误，暂不实现
    return True

**Comment by 5carecrow** [comment]
thx
