### ISSUE TITLE
Cannot compile lanms - ld: library not found for -lpython3.4m

### ISSUE THREAD

**Issue by challengerlihan** [argman/EAST#113]
Below is the error. It seems that it can't find -lpython3.4m. Can someone tell me how to fix it? Thanks!

1 warning generated.
ld: library not found for -lpython3.4m
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [adaptor.so] Error 1
Traceback (most recent call last):
  File "eval.py", line 9, in <module>
    import lanms
  File "/Users/challenger/GitHub/EAST/lanms/__init__.py", line 8, in <module>
    raise RuntimeError('Cannot compile lanms: {}'.format(BASE_DIR))
RuntimeError: Cannot compile lanms: /Users/challenger/GitHub/EAST/lanms

**Comment by zxytim** [comment]
sudo apt install python3-dev

**Comment by tsing-cv** [comment]
@zxytim, I tried your method, but still cannot solve this problem
