### ISSUE TITLE
horizontal text detection

### ISSUE THREAD

**Issue by balajiwix** [argman/EAST#135]
text_polys[:, :, 0] *= resize_ratio_3_x
IndexError: too many indices for array
poly in wrong direction
poly in wrong direction
invalid poly
invalid poly
Traceback (most recent call last):
  File "/home/ubuntu/balaji/text detection/icdar.py", line 669, in generator

poly in wrong direction
invalid poly
invalid poly
Traceback (most recent call last):
  File "/home/ubuntu/sabari/OCR Extraction/icdar.py", line 669, in generator
    text_polys[:, :, 0] *= resize_ratio_3_x
IndexError: too many indices for array
poly in wrong direction
Step 000000, model loss 0.0172, total loss 0.0496, 11.56 seconds/step, 1.38 examples/second
poly in wrong direction
poly in wrong direction

why i am getting poly in wrong direction?

**Comment by balajiwix** [comment]
text_polys, text_tags = load_annoataion(txt_fn)
  File "/home/ubuntu/sabari/OCR Extraction/icdar.py", line 61, in load_annoataion
    x1, y1, x2, y2, x3, y3, x4, y4 = list(map(float, line[:8]))
[101.txt](https://github.com/argman/EAST/files/1889941/101.txt)

ValueError: could not convert string to float:

i have changed the icdar text file in correct format but i am getting this error

**Comment by wangjianyuweg** [comment]
> text_polys, text_tags = load_annoataion(txt_fn)
> File "/home/ubuntu/sabari/OCR Extraction/icdar.py", line 61, in load_annoataion
> x1, y1, x2, y2, x3, y3, x4, y4 = list(map(float, line[:8]))
> [101.txt](https://github.com/argman/EAST/files/1889941/101.txt)
> 
> ValueError: could not convert string to float:
> 
> i have changed the icdar text file in correct format but i am getting this error

@balajiwix Hi, I meet the same problem, did you solved it?
