### ISSUE TITLE
Failed to find any matching files for /tmp/resnet_v1_50.ckpt

### ISSUE THREAD

**Issue by YanShuang17** [argman/EAST#147]
when i began to train model, error occured:
```
ys@ysubuntu:~/tensorflow/EAST$ python multigpu_train.py --gpu_list=0 --input_size=512 --batch_size_per_gpu=14 --checkpoint_path=/tmp/east_icdar2015_resnet_v1_50_rbox/ \
> --text_scale=512 --training_data_path=/data/ocr/icdar2015/ --geometry=RBOX --learning_rate=0.0001 --num_readers=24 \
> --pretrained_model_path=/tmp/resnet_v1_50.ckpt
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
('resnet_v1_50/block1', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(256)]))
('resnet_v1_50/block2', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(512)]))
('resnet_v1_50/block3', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(1024)]))
('resnet_v1_50/block4', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(2048)]))
Shape of f_0 (?, ?, ?, 2048)
Shape of f_1 (?, ?, ?, 512)
Shape of f_2 (?, ?, ?, 256)
Shape of f_3 (?, ?, ?, 64)
Shape of h_0 (?, ?, ?, 2048), g_0 (?, ?, ?, 2048)
Shape of h_1 (?, ?, ?, 128), g_1 (?, ?, ?, 128)
Shape of h_2 (?, ?, ?, 64), g_2 (?, ?, ?, 64)
Shape of h_3 (?, ?, ?, 32), g_3 (?, ?, ?, 32)
Traceback (most recent call last):
  File "multigpu_train.py", line 180, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "multigpu_train.py", line 136, in main
    ignore_missing_vars=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/framework/python/ops/variables.py", line 638, in assign_from_checkpoint_fn
    reader = pywrap_tensorflow.NewCheckpointReader(model_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 110, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern), status)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /tmp/resnet_v1_50.ckpt
```
it may be the path problem, but i did put `resnet_v1_50.ckpt` file under the `./EAST/tmp/ ` folder.
below is my file tree:
```
─ EAST
│   ├── data
│   │   └── ocr
│   │       ├── icdar2015
│   │       └── rename.py
│   ├── data_util.py
│   ├── data_util.pyc
│   ├── demo_images
│   │   ├── img_10.jpg
│   │   ├── img_14.jpg
│   │   ├── img_26.jpg
│   │   ├── img_2.jpg
│   │   ├── img_75.jpg
│   │   └── web-demo.png
│   ├── deploy.sh
│   ├── eval.py
│   ├── icdar.py
│   ├── icdar.pyc
│   ├── __init__.py
│   ├── lanms
│   │   ├── adaptor.cpp
│   │   ├── adaptor.so
│   │   ├── include
│   │   │   ├── clipper
│   │   │   └── pybind11
│   │   ├── __init__.py
│   │   ├── __init__.pyc
│   │   ├── lanms.h
│   │   ├── __main__.py
│   │   └── Makefile
│   ├── LICENSE
│   ├── locality_aware_nms.py
│   ├── locality_aware_nms.pyc
│   ├── model.py
│   ├── model.pyc
│   ├── multigpu_train.py
│   ├── nets
│   │   ├── __init__.py
│   │   ├── __init__.pyc
│   │   ├── resnet_utils.py
│   │   ├── resnet_utils.pyc
│   │   ├── resnet_v1.py
│   │   └── resnet_v1.pyc
│   ├── readme.md
│   ├── requirements.txt
│   ├── run_demo_server.py
│   ├── static
│   │   └── css
│   │       └── app.css
│   ├── templates
│   │   └── index.html
│   ├── tmp
│   │   ├── east_icdar2015_resnet_v1_50_rbox
│   │   │   ├── checkpoint
│   │   │   ├── model.ckpt-49491.data-00000-of-00001
│   │   │   ├── model.ckpt-49491.index
│   │   │   └── model.ckpt-49491.meta
│   │   ├── images
│   │   │   └── img_1.jpg
│   │   └── resnet_v1_50.ckpt
│   └── training_samples
│       ├── img_1.jpg
│       ├── img_1.txt
│       ├── img_2.jpg
│       └── img_2.txt

```
Besides that , I also can't run eval.py correctly:
```
ys@ysubuntu:~/tensorflow/EAST$ python eval.py --test_data_path=/tmp/images/ --gpu_list=0 --checkpoint_path=/tmp/east_icdar2015_resnet_v1_50_rbox/ \
> --output_dir=/tmp/
make: Entering directory '/home/ys/tensorflow/EAST/lanms'
make: 'adaptor.so' is up to date.
make: Leaving directory '/home/ys/tensorflow/EAST/lanms'
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
('resnet_v1_50/block1', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(256)]))
('resnet_v1_50/block2', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(512)]))
('resnet_v1_50/block3', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(1024)]))
('resnet_v1_50/block4', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(2048)]))
Shape of f_0 (?, ?, ?, 2048)
Shape of f_1 (?, ?, ?, 512)
Shape of f_2 (?, ?, ?, 256)
Shape of f_3 (?, ?, ?, 64)
Shape of h_0 (?, ?, ?, 2048), g_0 (?, ?, ?, 2048)
Shape of h_1 (?, ?, ?, 128), g_1 (?, ?, ?, 128)
Shape of h_2 (?, ?, ?, 64), g_2 (?, ?, ?, 64)
Shape of h_3 (?, ?, ?, 32), g_3 (?, ?, ?, 32)
2018-04-23 14:15:19.369929: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-04-23 14:15:19.369949: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-04-23 14:15:19.369953: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-04-23 14:15:19.369957: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-04-23 14:15:19.369960: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2018-04-23 14:15:19.487540: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-04-23 14:15:19.487762: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties: 
name: GeForce GTX 1080 Ti
major: 6 minor: 1 memoryClockRate (GHz) 1.6575
pciBusID 0000:01:00.0
Total memory: 10.91GiB
Free memory: 10.13GiB
2018-04-23 14:15:19.487774: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 
2018-04-23 14:15:19.487778: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y 
2018-04-23 14:15:19.487783: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0)
Traceback (most recent call last):
  File "eval.py", line 194, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "eval.py", line 145, in main
    model_path = os.path.join(FLAGS.checkpoint_path, os.path.basename(ckpt_state.model_checkpoint_path))
AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'
```
What's wrong ???

**Comment by luisbouca** [comment]
did you find the problem ??
if so please post the solution because i am having the same problem

**Comment by enathang** [comment]
The problem is the checkpoint_path flag isn't pointing to a valid checkpoint, so tf.get_checkpoint_state() returns None (line 144). Double check the checkpoint_path is correct.

I ran into this error, then discovered 'east_icdar2015_resnet_v1_50_rbox/' worked but '/east_icdar2015_resnet_v1_50_rbox/' did not for me (note the first slash). Small details like that are hard to find but WILL lead to errors.

**Comment by enathang** [comment]
Sure! The only modification I made in the code was to change line 13 (where the checkpoint_path flag is declared in both eval.py and multigpu_train.py to:
   tf.app.flags.DEFINE_string('checkpoint_path', 'east_icdar2015_resnet_v1_50_rbox/', '')

Or, if you want to pass in the checkpoint as a argument:
   python multigpu_train.py --checkpoint_path=east_icdar2015_resnet_v1_50_rbox/

Again, the path you should give is dependent on where the checkpoint is actually located (I had the resnet folder in the same location as eval.py/multigpu_train.py).

**Comment by IngleJaya95** [comment]
If in case someone is giving --checkpoint_path=**/**tmp/xyz/ , rthen change it to --checkpoint_path=tmp/xyz/..(just remove slash)
