### ISSUE TITLE
There is a problem when train the datasets.

### ISSUE THREAD

**Issue by loulan-D** [argman/EAST#151]
There is no problem when  1000 examples are provided  . 
but when i use 5000 examples to train there is a error:

Traceback (most recent call last):
  File "/home/ubuntu/桌面/EAST-train-5.2/EAST-train-5.1/east/icdar.py", line 603, in generator
    h, w, _ = im.shape
AttributeError: 'NoneType' object has no attribute 'shape'

I want to know the reason. thanks

**Comment by maichm** [comment]
Use `print(image_name)` in your code to debug. I think there must be some broken image in your images directory.

**Comment by rohitpattnaik** [comment]
Hello .... What is the annotation tool you have used for your images please ?

**Comment by eliyaz-virtech** [comment]
pls share the annotation tool used ?

**Comment by brealisty** [comment]
> There is no problem when 1000 examples are provided .
> but when i use 5000 examples to train there is a error:
> 
> Traceback (most recent call last):
> File "/home/ubuntu/桌面/EAST-train-5.2/EAST-train-5.1/east/icdar.py", line 603, in generator
> h, w, _ = im.shape
> AttributeError: 'NoneType' object has no attribute 'shape'
> 
> I want to know the reason. thanks

have u solved this problem?
