### ISSUE TITLE
FindFirstFile failed for: /tmp/east_icdar2015_resnet_v1_50_rbox 

### ISSUE THREAD

**Issue by lijian-1994** [argman/EAST#203]
when I run the command in windows:
python multigpu_train.py  --input_size=512 --batch_size_per_gpu=2 --checkpoint_path=G:/tensorflow/EAST-master/tmp/east_icdar2015_resnet_v1_50_rbox/ --text_scale=512 --training_data_path=G:\tensorflow\EAST-master\training_samples\  --geometry=RBOX --learning_rate=0.0001 --num_readers=1  --pretrained_model_path=G:\tensorflow\EAST-master/tmp/resnet_v1_50.ckpt
error occured:
`continue training from previous checkpoint
Traceback (most recent call last):
  File "multigpu_train.py", line 180, in <module>
    tf.app.run()
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "multigpu_train.py", line 140, in main
    ckpt = tf.train.latest_checkpoint(FLAGS.checkpoint_path)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1841, in latest_checkpoint
    if file_io.get_matching_files(v2_path) or file_io.get_matching_files(
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 342, in get_matching_files
    for single_filename in filename
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: FindFirstFile failed for: /tmp/east_icdar2015_resnet_v1_50_rbox : ϵͳ\udcd5Ҳ\udcbb\udcb5\udcbdָ\udcb6\udca8\udcb5\udcc4·\udcbe\udcb6\udca1\udca3
; No such process`
It iss.
when I run the command in unix:
` python multigpu_train.py  --input_size=512 --batch_size_per_gpu=14 --checkpoint_path=/home/XXX/lijian/EAST-master/tmp/east_icdar2015_resnet_v1_50_rbox  --text_scale=512 --training_data_path=./training_samples/ --geometry=RBOX --learning_rate=0.0001 --num_readers=24`
It is stuck at :
`Generator use 10 batches for buffering, this may take a while, you can tune this yourself.
2 training images in ./training_samples/
2 training images in ./training_samples/
2 training images in ./training_samples/
2 training images in ./training_samples/
2 training images in ./training_samples/
2 training images in ./training_samples/
2 training images in ./training_samples/
2 training images in ./training_samples/
2 training images in ./training_samples/
2 training images in ./training_samples/
2 training images in ./training_samples/
2 training images in ./training_samples/
2 training images in ./training_samples/`
who can help me?

**Comment by IngleJaya95** [comment]
reducing reader size helped me.

**Comment by lijian-1994** [comment]
> reducing reader size helped me.
I tried it but it didn't work.

**Comment by pitchayakit** [comment]
2 training not enough so you can try more than 2 training images or try to use batch = 2

**Comment by yyf7329081** [comment]
hello, have you worked out this problem? i met the same problem.
