### ISSUE TITLE
Win10 build  lanms fatal error LNK1112

### ISSUE THREAD

**Issue by Phantom1003** [argman/EAST#204]
After I run the demo, it told me:
(crnntf) C:\Users\89293\Desktop\002>python run_demo_server.py --checkpoint-path tmp/east_icdar2015_resnet_v1_50_rbox/checkpoint
 * Running on http://0.0.0.0:8769/ (Press CTRL+C to quit)
I can get the demo at http://localhost:8769/   instead of 0.0.0.0:8769, but when I submit a picture, it turns to a page with:
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
and the output in shell is:
Traceback (most recent call last):
  File "E:\Anaconda\envs\crnntf\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Anaconda\envs\crnntf\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Anaconda\envs\crnntf\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\Anaconda\envs\crnntf\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "E:\Anaconda\envs\crnntf\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Anaconda\envs\crnntf\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "run_demo_server.py", line 204, in index_post
    rst = get_predictor(checkpoint_path)(img)
  File "run_demo_server.py", line 41, in get_predictor
    import lanms
  File "C:\Users\89293\Desktop\002\lanms\__init__.py", line 7, in <module>
    if subprocess.call(['make', '-C', BASE_DIR]) != 0:  # return value
  File "E:\Anaconda\envs\crnntf\lib\subprocess.py", line 247, in call
    with Popen(*popenargs, **kwargs) as p:
  File "E:\Anaconda\envs\crnntf\lib\subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "E:\Anaconda\envs\crnntf\lib\subprocess.py", line 957, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

Then I goto build lanms：
C:\Users\89293\Desktop\002\lanms>cl adaptor.cpp ./include/clipper/clipper.cpp /I ./include /I "E:\Anaconda\include" /LD /Fe:adaptor.pyd /link/LIBPATH:"E:\Anaconda\libs"
用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.12.25835 版
版权所有(C) Microsoft Corporation。保留所有权利。

adaptor.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.12.25827\include\xlocale(313): warning C4530: 使用了 C++ 异常处理程序，但未启用展开语义。请指定 /EHsc
clipper.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.12.25827\include\xlocale(313): warning C4530: 使用了 C++ 异常处理程序，但未启用展开语义。请指定 /EHsc
./include/clipper/clipper.cpp(3794): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
正在生成代码...
Microsoft (R) Incremental Linker Version 14.12.25835.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/dll
/implib:adaptor.lib
/out:adaptor.pyd
/LIBPATH:E:\Anaconda\libs
adaptor.obj
clipper.obj
python37.lib(python37.dll) : fatal error LNK1112: 模块计算机类型“x64”与目标计算机类型“x86”冲突
How to solve this？
please help me, thanks!

**Comment by yongcong1415** [comment]
you system is x64?
