### ISSUE TITLE
Training errors 'Cross point does not exist'

### ISSUE THREAD

**Issue by rolai** [argman/EAST#21]
When I train the model with dataset ICDAR2015, I meet the error:

```
Cross point does not exist
Traceback (most recent call last):
  File "/home/lairf/EAST/icdar.py", line 657, in generator
    score_map, geo_map, training_mask = generate_rbox((new_h, new_w), text_polys, text_tags)
  File "/home/lairf/EAST/icdar.py", line 520, in generate_rbox
    if point_dist_to_line(p1, new_p2, p0) > point_dist_to_line(p1, new_p2, p3):
  File "/home/lairf/EAST/icdar.py", line 248, in point_dist_to_line
    return np.linalg.norm(np.cross(p2 - p1, p1 - p3)) / np.linalg.norm(p2 - p1)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
```
Why it happens? Does it influence the training result?

**Comment by argman** [comment]
@rolai , i think its cause by some unusual polygons(maybe concave), it does not influence the traning result.
