### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'

### ISSUE THREAD

**Issue by harshalcse** [argman/EAST#212]
While Running following command:
python eval.py --test_data_path=/tmp/images/ --gpu_list=0 --checkpoint_path=/tmp/east_icdar2015_resnet_v1_50_rbox/ \
--output_dir=/tmp/

OS: Ubuntu 18.04
RAM: 8 GB

Traceback (most recent call last):
  File "eval.py", line 194, in <module>
    tf.app.run()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "eval.py", line 145, in main
    model_path = os.path.join(FLAGS.checkpoint_path, os.path.basename(ckpt_state.model_checkpoint_path))
AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'

**Comment by JustinhoCHN** [comment]
I got that error too. Waiting for help.
OS: ubuntu 16.04.5
tensorflow: 1.7.0
cuda: 9.0
cudnn: 7.1

**Comment by harshalcse** [comment]
@JustinhoCHN  what new in command

**Comment by JustinhoCHN** [comment]
@harshalcse check carefully, I removed some '/', as #147 mentioned.

**Comment by Simrandee** [comment]
Can't seem to resolve this error even though everything is in the EAST folder. Please help at the earliest

**Comment by tianmaxingkonggrant** [comment]
--checkpoint_path=east_icdar2015_resnet_v1_50_rbox/ use absolute path

**Comment by jajoe** [comment]
Hello 

I had the same error. It was due to the model that I copied to the checkpoint_path.

In the README, you can find several models. I downloaded two archives : resnet_v1_50_2016_08_28.tar.gz and east_icdar2015_resnet_v1_50_rbox.zip.

The archive resnet_v1... included a file resnet_v1_50.ckpt. When I copy this file in the checkpoint_path, it didn't work. 
The archive east_icdar2015_reset_v1... included four files. When I copy these files in the checkpoint_path, it works.

**Comment by Doan-Nguyen** [comment]
hi @harshalcse , i dont know do u have solution ?
My solution: 
+ check cmd to run code: 
$  python2 eval.py --test_data_path=demo_images/ --gpu_list=0 --checkpoint_path=east_icdar2015_resnet_v1_50_rbox/ --output_path=tmp/output/

+ open checkpoint file & check path correct ? Change checkpoint path depend your laptop.

Good luck for you.

**Comment by Rakesh-MS-91** [comment]
@Doan-Nguyen @JustinhoCHN 
hi,
After running the above mentioned code, will I get the output image with bounding box in the output folder (--output_path=tmp/output/)

**Comment by FlyBird7** [comment]
I just modify the code.
Initial code:
model_path = os.path.join(FLAGS.checkpoint_path, os.path.basename(ckpt_state.model_checkpoint_path))
After modification：
model_path = os.path.join(FLAGS.checkpoint_path, "model.ckpt-95025")
model.ckpt-95025  from the file checkpoint_path。
