### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by zhuliqian** [argman/EAST#222]
/home/chase/EAST-master/icdar.py:249: RuntimeWarning: invalid value encountered in float_scalars
  return np.linalg.norm(np.cross(p2 - p1, p1 - p3)) / np.linalg.norm(p2 - p1)
Cross point does not exist
Traceback (most recent call last):
  File "/home/chase/EAST-master/icdar.py", line 659, in generator
    score_map, geo_map, training_mask = generate_rbox((new_h, new_w), text_polys, text_tags)
  File "/home/chase/EAST-master/icdar.py", line 521, in generate_rbox
    if point_dist_to_line(p1, new_p2, p0) > point_dist_to_line(p1, new_p2, p3):
  File "/home/chase/EAST-master/icdar.py", line 249, in point_dist_to_line
    return np.linalg.norm(np.cross(p2 - p1, p1 - p3)) / np.linalg.norm(p2 - p1)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

**Comment by xxlxx1** [comment]
@zhuliqian i meet the same error and then another, have you soled the problem?

Traceback (most recent call last):
  File "/data/xlxia/code/EAST/icdar.py", line 658, in generator
    score_map, geo_map, training_mask = generate_rbox((new_h, new_w), text_polys, text_tags)
  File "/data/xlxia/code/EAST/icdar.py", line 520, in generate_rbox
    if point_dist_to_line(p1, new_p2, p0) > point_dist_to_line(p1, new_p2, p3):
  File "/data/xlxia/code/EAST/icdar.py", line 248, in point_dist_to_line
    return np.linalg.norm(np.cross(p2 - p1, p1 - p3)) / np.linalg.norm(p2 - p1

**Comment by bit2270943907** [comment]
i meet the same error ,i give up multigpu,and try only  one gpu,the problem is solved

**Comment by ganliqiang** [comment]
meet the same error  who can help us fix this problem

**Comment by 1LOVESJohnny** [comment]
If ignore this problem, will it influence the training result?

**Comment by xxlxx1** [comment]
@1LOVESJohnny my result seems right

**Comment by 1LOVESJohnny** [comment]
> @1LOVESJohnny my result seems right

Thanks for your reply. Can I ask if you've the problem solved?

**Comment by xxlxx1** [comment]
@1LOVESJohnny i just ignore this error
