### ISSUE TITLE
Import error when trying eval.py

### ISSUE THREAD

**Issue by roger12337** [argman/EAST#234]
I have got the error below when I try eval.py.

Find 5 images
194 text boxes before nms
Traceback (most recent call last):
  File "eval.py", line 194, in <module>
    tf.app.run()
  File "D:\Software\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "eval.py", line 160, in main
    boxes, timer = detect(score_map=score, geo_map=geometry, timer=timer)
  File "eval.py", line 98, in detect
    boxes = lanms.merge_quadrangle_n9(boxes.astype('float32'), nms_thres)
  File "D:\Tensorflow\text-detection\EAST-master\lanms\__init__.py", line 12, in merge_quadrangle_n9
    from .adaptor import merge_quadrangle_n9 as nms_impl
ImportError: DLL load failed: 找不到指定的模块。

It seems I do not import adaptor correctly. I have compiled lamns and adaptor.pyd is generated. I run in Win10 environment. Can anyone help me on this? Thanks a lot!

**Comment by JJuaner** [comment]
I encounter the same question, have you solved it?  Thank you!!!!!!!!!!

**Comment by AlexanderMakarov95** [comment]
bump! anyone solved this yet?

**Comment by BYJRK** [comment]
Me also waiting for a life saver, and before that, using `locality_aware_nms.py` instead of `lanms` might be a sloowwwww solution

**Comment by BYJRK** [comment]
in `lanms/`, edit the `Makefile`, and the script looks like:

```shell
CXXFLAGS = -I include  -std=c++11 -O3 $(shell python3-config --cflags)
LDFLAGS = $(shell python3-config --ldflags)

DEPS = lanms.h $(shell find include -xtype f)
CXX_SOURCES = adaptor.cpp include/clipper/clipper.cpp

...
```

Notice the `$(shell python-config --cflags)` at line 1. Try this command in your terminal, and you'll get information like:

```shell
-I/data/home/username/anaconda3/include/python3.7m -I/data/home/username/anaconda3/include/python3.7m  -Wno-unused-result -Wsign-compare -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe  -fdebug-prefix-map==/usr/local/src/conda/- -fdebug-prefix-map==/usr/local/src/conda-prefix -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -flto -flto -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -g -DNDEBUG -fwrapv -O3 -Wall
```

Here, remove `-fno-plt`, `-mtune=haswell`, and paste the rest of information into `Makefile` and replace `$(shell python3-config --cflags)` at line 1 (line 2 doesn't really matter). Save and quit. I hope then you can `make`.

**Comment by KKDDD** [comment]
I have same error, do you solve it?

**Comment by skyhdev** [comment]
File "D:\Tensorflow\text-detection\EAST-master\lanms_init.py", line 12, in merge_quadrangle_n9
from .adaptor import merge_quadrangle_n9 as nms_impl
ImportError: DLL load failed
How can I solve it on windows 10?
