### ISSUE TITLE
NoneType has no len() for shapely

### ISSUE THREAD

**Issue by saharudra** [argman/EAST#247]
While running the code, I am getting the following error on files randomly. I have tried both with python2 and python3.

```
Traceback (most recent call last):
  File "main.py", line 148, in <module>
    main(args.config)
  File "main.py", line 117, in main
    train(train_loader, model, criterion, scheduler, optimizer, epoch, cfg)
  File "main.py", line 36, in train
    for i, (img, score_map, geo_map, training_mask) in enumerate(train_loader):
  File "/2scratch/anaconda2/envs/pytorch/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 322, in __next__
    return self._process_next_batch(batch)
  File "/2scratch/anaconda2/envs/pytorch/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/2scratch/anaconda2/envs/pytorch/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/1scratch/abhishek/verisk_projects/TDR/TDR_PyTorch/data_utils.py", line 1009, in __getitem__
    random_scale = np.array([0.5, 1.0, 2.0, 3.0]), background_ratio = 3./8)
  File "/1scratch/abhishek/verisk_projects/TDR/TDR_PyTorch/data_utils.py", line 915, in image_label
    score_map, geo_map, training_mask = generate_rbox((new_h, new_w), text_polys, text_tags)
  File "/1scratch/abhishek/verisk_projects/TDR/TDR_PyTorch/data_utils.py", line 748, in generate_rbox
    areas = [Polygon(t).area for t in fitted_parallelograms]
  File "/2scratch/anaconda2/envs/pytorch/lib/python2.7/site-packages/shapely/geometry/polygon.py", line 240, in __init__
    ret = geos_polygon_from_py(shell, holes)
  File "/2scratch/anaconda2/envs/pytorch/lib/python2.7/site-packages/shapely/geometry/polygon.py", line 494, in geos_polygon_from_py
    ret = geos_linearring_from_py(shell)
  File "shapely/speedups/_speedups.pyx", line 319, in shapely.speedups._speedups.geos_linearring_from_py
    n = len(ob[0])
TypeError: object of type 'NoneType' has no len()
```

**Comment by saharudra** [comment]
Adding back the `try except` catch in `data_utils.py` in the method `image_label` makes it go around this issue.

**Comment by sulata2** [comment]
> Adding back the `try except` catch in `data_utils.py` in the method `image_label` makes it go around this issue.

even i am facing same issue.. anyone can help
