### ISSUE TITLE
Error while running eval.py for Python version mismatch

### ISSUE THREAD

**Issue by Haruo195** [argman/EAST#261]
Hi, After putting the checkpoints of **Models trained on ICDAR 2013 (training set) + ICDAR 2015 (training set)** inside checkpoints/east_icdar2015_resnet_v1_50_rbox/ ,I am trying to run the eval.py as follows:

`python eval.py --test_data_path=demo_images/ --gpu_list=0 --checkpoint_path=checkpoints/east_icdar2015_resnet_v1_50_rbox/ --output_path=output/`

I am getting the following error

make: Entering directory '/home/EAST_arg/lanms'
make: 'adaptor.so' is up to date.
make: Leaving directory '/home/EAST_arg/lanms'
WARNING:tensorflow:From /home/.virtualenvs/cv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
resnet_v1_50/block1 (?, ?, ?, 256)
resnet_v1_50/block2 (?, ?, ?, 512)
resnet_v1_50/block3 (?, ?, ?, 1024)
resnet_v1_50/block4 (?, ?, ?, 2048)
Shape of f_0 (?, ?, ?, 2048)
Shape of f_1 (?, ?, ?, 512)
Shape of f_2 (?, ?, ?, 256)
Shape of f_3 (?, ?, ?, 64)
Shape of h_0 (?, ?, ?, 2048), g_0 (?, ?, ?, 2048)
Shape of h_1 (?, ?, ?, 128), g_1 (?, ?, ?, 128)
Shape of h_2 (?, ?, ?, 64), g_2 (?, ?, ?, 64)
Shape of h_3 (?, ?, ?, 32), g_3 (?, ?, ?, 32)
2019-04-16 14:46:28.094374: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-04-16 14:46:28.222951: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x6231b00 executing computations on platform CUDA. Devices:
2019-04-16 14:46:28.223002: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): Quadro P2000, Compute Capability 6.1
2019-04-16 14:46:28.226088: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3696090000 Hz
2019-04-16 14:46:28.226732: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x629da70 executing computations on platform Host. Devices:
2019-04-16 14:46:28.226764: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-04-16 14:46:28.226994: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: Quadro P2000 major: 6 minor: 1 memoryClockRate(GHz): 1.4805
pciBusID: 0000:65:00.0
totalMemory: 4.93GiB freeMemory: 4.62GiB
2019-04-16 14:46:28.227021: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-04-16 14:46:28.227932: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-04-16 14:46:28.227951: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-04-16 14:46:28.227966: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-04-16 14:46:28.228155: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4426 MB memory) -> physical GPU (device: 0, name: Quadro P2000, pci bus id: 0000:65:00.0, compute capability: 6.1)
Restore from checkpoints/east_icdar2015_resnet_v1_50_rbox/model.ckpt-49491
WARNING:tensorflow:From /home/.virtualenvs/cv/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Find 6 images
225 text boxes before nms
Traceback (most recent call last):
  File "eval.py", line 196, in <module>
    tf.app.run()
  File "/home/.virtualenvs/cv/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "eval.py", line 162, in main
    boxes, timer = detect(score_map=score, geo_map=geometry, timer=timer)
  File "eval.py", line 100, in detect
    boxes = lanms.merge_quadrangle_n9(boxes.astype('float32'), nms_thres)
  File "/home/EAST_arg/lanms/__init__.py", line 12, in merge_quadrangle_n9
    from .adaptor import merge_quadrangle_n9 as nms_impl
ImportError: Python version mismatch: module was compiled for version 3.5, while the interpreter is running version 3.6.

Working on a machine with Ubuntu 16.04 and python 3.6.

The system has python 2.7, python 3.5 and python 3.6 installed in it.
Currently both pip and pip3 are pointed to python 3.6

Thank you for your time.

**Comment by yangtao19920109** [comment]
change the g++ paramater

**Comment by saharudra** [comment]
@yangtao19920109 Can you please elaborate on how to do that?

**Comment by yuxiaomu** [comment]
@yangtao19920109 请问具体怎么做啊，我现在也遇到这个问题

**Comment by yangtao19920109** [comment]
我已经忘了，记得当时像是
把g++的路径添加到了makefile文件里



发自我的iPhone


------------------ Original ------------------

**Comment by tumbleintoyourheart** [comment]
Hi,
Has anyone fixed this?

**Comment by baolinhtb** [comment]
1. Open **Makefile** in **lanms** folder
2. Change **pythonx.x-config** in two first lines to your current python version.
ex:
CXXFLAGS = -I include  -std=c++11 -O3 $(shell python3.7-config --cflags)
LDFLAGS = $(shell python3.7-config --ldflags)
3. Delete **adaptor.so**
4. Run command **make**.

**Comment by Manuj229** [comment]
> 1. Open **Makefile** in **lanms** folder
> 2. Change **pythonx.x-config** in two first lines to your current python version.
>    ex:
>    CXXFLAGS = -I include  -std=c++11 -O3 $(shell python3.7-config --cflags)
>    LDFLAGS = $(shell python3.7-config --ldflags)
> 3. Delete **adaptor.so**
> 4. Run command **make**.

Where is this adaptor.so????

**Comment by ND15** [comment]
> > 1. Open **Makefile** in **lanms** folder
> > 2. Change **pythonx.x-config** in two first lines to your current python version.
> >    ex:
> >    CXXFLAGS = -I include  -std=c++11 -O3 $(shell python3.7-config --cflags)
> >    LDFLAGS = $(shell python3.7-config --ldflags)
> > 3. Delete **adaptor.so**
> > 4. Run command **make**.
> 
> Where is this adaptor.so????

The adaptor.so is not visible. It was not visible in my folder. But you can just run the command **rm adaptor.so** on linux or **!rm adaptor.so** on colab and it will remove the file. After that run the command make. This method worked for me.
