### ISSUE TITLE
running eval.py; undefined symbol: _Py_ZeroStruct

### ISSUE THREAD

**Issue by PaoWuXian2L** [argman/EAST#263]
Error when i running eval.py, 

Traceback (most recent call last):
  File "eval.py", line 196, in <module>
    tf.app.run()
  File "/home/pwx/anaconda3/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "eval.py", line 162, in main
    boxes, timer = detect(score_map=score, geo_map=geometry, timer=timer)
  File "eval.py", line 100, in detect
    boxes = lanms.merge_quadrangle_n9(boxes.astype('float32'), nms_thres)
  File "/home/pwx/EAST-master/lanms/__init__.py", line 12, in merge_quadrangle_n9
    from .adaptor import merge_quadrangle_n9 as nms_impl
ImportError: /home/pwx/EAST-master/lanms/adaptor.so: undefined symbol: _Py_ZeroStruct

maybe it because of version mismatch? somebody advises me amending the "makefile", but i don't know how to do it.

my system: Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-45-generic x86_64)
using anaconda3-2019.03
python                    3.7.3                h0371630_0
python-dateutil           2.8.0                    py37_0
python-libarchive-c       2.8                      py37_6

what should i do?
thank you

**Comment by piciore** [comment]
I have the same problem (on the same system)

**Comment by PaoWuXian2L** [comment]
> I have the same problem (on the same system)

i have solved
if you just want to test,, you can change the lanms.merge_quadrangle_n9() in eval.py to nms_locality.nms_locality() There's no error. nms_locality.nms_locality() is a python implemention, its much slower than c++ code.
Otherwise, you can install lower g++/gcc

**Comment by piciore** [comment]
Thanks a lot! It solved the problem and now eval.py works fine!
But, if i want to use lanms.merge_quadrangle_n9() for better performance, do you know what i should do?

**Comment by tlsgb456** [comment]
@piciore Go to lanms directory, and change python-config to python3-config in Makefile. And then make clean and make. In my case, it works.

**Comment by Yangchao0053** [comment]
升级gcc.  如果还是不行，  是不是看了这个  ‘-fno-plt’把MKfile改了，改回去就行了

**Comment by Yangchao0053** [comment]
升级gcc.    傻瓜命令   sudo apt-get upgrade

**Comment by vuquocan1987** [comment]
When I change the python3-config to python-config. I had another error:
"
undefined symbol: _Py_ZeroStruct

"

What should I do :-?
