### ISSUE TITLE
i get error in lanms EAST

### ISSUE THREAD

**Issue by aztbzkrt** [argman/EAST#274]
I runing this below code

```
import subprocess
import os
import numpy as np

BASE_DIR = os.path.dirname(os.path.realpath(__file__))

if subprocess.call(['make', '-C', BASE_DIR]) != 0:  # return value
    raise RuntimeError('Cannot compile lanms: {}'.format(BASE_DIR))


def merge_quadrangle_n9(polys, thres=0.3, precision=10000):
    from .adaptor import merge_quadrangle_n9 as nms_impl
    if len(polys) == 0:
        return np.array([], dtype='float32')
    p = polys.copy()
    p[:,:8] *= precision
    ret = np.array(nms_impl(p, thres), dtype='float32')
    ret[:,:8] /= precision
    return ret
```

i got this error

```
Traceback (most recent call last):
  File "C:\Users\LENOVA\Desktop\east\EAST-master\eval.py", line 11, in <module>
    from lanms import *
  File "C:\Users\LENOVA\Desktop\east\EAST-master\lanms\__init__.py", line 7, in <module>
    if subprocess.call(['make', '-C', BASE_DIR]) != 0:  # return value
  File "C:\Users\LENOVA\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\LENOVA\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Users\LENOVA\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

Please help me

**Comment by rashanliyanage** [comment]
Hii @aztbzkrt 

did you solve the problem.would you please tell me how it is done

**Comment by aztbzkrt** [comment]
Hi @rashansamith 

Sorry. I couldn't solve the problem. If you too solve the problem you, would you let me know...

Thanks,

**Comment by aztbzkrt** [comment]
++

**Comment by wangwangww** [comment]
+1

**Comment by zuoyuwei** [comment]
run this code based on ubuntu system, it may solve this problem.
