### ISSUE TITLE
RuntimeError: Cannot compile lanms:

### ISSUE THREAD

**Issue by jun214384468** [argman/EAST#331]
/home/yan/anaconda3/envs/py36/bin/python /home/yan/disk/All_python_Text/EAST-master/eval.py
make: Entering directory '/home/yan/disk/All_python_Text/EAST-master/lanms'
make: python3-config：命令未找到
make: python3-config：命令未找到
g++ -o adaptor.so -I include  -std=c++11 -O3   adaptor.cpp include/clipper/clipper.cpp --shared -fPIC
In file included from include/pybind11/pytypes.h:12:0,
                 from include/pybind11/cast.h:13,
                 from include/pybind11/attr.h:13,
                 from include/pybind11/pybind11.h:43,
                 from adaptor.cpp:1:
include/pybind11/common.h:100:20: fatal error: Python.h: 没有那个文件或目录
compilation terminated.
Makefile:10: recipe for target 'adaptor.so' failed
make: Leaving directory '/home/yan/disk/All_python_Text/EAST-master/lanms'
make: *** [adaptor.so] Error 1
Traceback (most recent call last):
  File "/home/yan/disk/All_python_Text/EAST-master/eval.py", line 9, in <module>
    import lanms
  File "/home/yan/disk/All_python_Text/EAST-master/lanms/__init__.py", line 8, in <module>
    raise RuntimeError('Cannot compile lanms: {}'.format(BASE_DIR))
RuntimeError: Cannot compile lanms: /home/yan/disk/All_python_Text/EAST-master/lanms

**Comment by lidongliang-cloud** [comment]
Try this:
1) open folder "lanms", 
2) change the name of the file "adapter.pcc" to "adapter.pyd", 
3) open the file "_init_.py" and delete/comment line 7-8. 

This works for me. Good luck :)

**Comment by Dive-frank** [comment]
yet ,I have meet this problem and solved:
make: python3-config："not found" that mean your python-dev is not install ,use "sudo apt-get intsall python3-dev".After install,this problem will ok.
