### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found

### ISSUE THREAD

**Issue by masterhimanshupoddar** [argman/EAST#338]
I think this error is because of the shapely package but I have installed this package still I am getting an error : 
```
Traceback (most recent call last):
  File "eval.py", line 8, in <module>
    import locality_aware_nms as nms_locality
  File "C:\Users\HPO2KOR\Desktop\Work\EAST-virtualenv\EAST_ICPR-master\locality_aware_nms.py", line 2, in <module>
    from shapely.geometry import Polygon
  File "C:\Users\HPO2KOR\Desktop\Work\EAST-virtualenv\eastvenv\lib\site-packages\shapely\geometry\__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "C:\Users\HPO2KOR\Desktop\Work\EAST-virtualenv\eastvenv\lib\site-packages\shapely\geometry\base.py", line 18, in <module>
    from shapely.coords import CoordinateSequence
  File "C:\Users\HPO2KOR\Desktop\Work\EAST-virtualenv\eastvenv\lib\site-packages\shapely\coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "C:\Users\HPO2KOR\Desktop\Work\EAST-virtualenv\eastvenv\lib\site-packages\shapely\geos.py", line 145, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
  File "C:\Users\HPO2KOR\Desktop\Work\EAST-virtualenv\eastvenv\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

**Comment by WoshiBoluo** [comment]
conda install -c conda-forge shapely
