### ISSUE TITLE
Ubuntu 18 demo server error

### ISSUE THREAD

**Issue by wiistriker** [argman/EAST#354]
Trying to run demo server on ubuntu. Tensorflow 1.15 with gpu and cuda installed

```
striker@striker-ubuntu-desktop:~/development/EAST$ python3 run_demo_server.py 
 * Running on http://0.0.0.0:8769/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 308-338-833
127.0.0.1 - - [16/Jul/2020 21:17:47] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [16/Jul/2020 21:17:47] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [16/Jul/2020 21:17:47] "GET /static/results/dummy_session_id/output.png HTTP/1.1" 404 -
Traceback (most recent call last):
  File "/home/striker/development/EAST/run_demo_server.py", line 226, in <module>
    main()
  File "/home/striker/development/EAST/run_demo_server.py", line 223, in main
    app.run('0.0.0.0', args.port)
  File "/home/striker/.local/lib/python3.6/site-packages/flask/app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "/home/striker/.local/lib/python3.6/site-packages/werkzeug/serving.py", line 1050, in run_simple
    run_with_reloader(inner, extra_files, reloader_interval, reloader_type)
  File "/home/striker/.local/lib/python3.6/site-packages/werkzeug/_reloader.py", line 337, in run_with_reloader
    reloader.run()
  File "/home/striker/.local/lib/python3.6/site-packages/werkzeug/_reloader.py", line 202, in run
    for filename in chain(_iter_module_files(), self.extra_files):
  File "/home/striker/.local/lib/python3.6/site-packages/werkzeug/_reloader.py", line 24, in _iter_module_files
    filename = getattr(module, "__file__", None)
  File "/home/striker/.local/lib/python3.6/site-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/home/striker/.local/lib/python3.6/site-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tensorflow_core.keras'
```

**Comment by lamanhdai** [comment]
```
127.0.0.1 - - [29/Jul/2020 09:59:47] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [29/Jul/2020 09:59:47] "GET /static/css/app.css HTTP/1.1" 200 -
127.0.0.1 - - [29/Jul/2020 09:59:47] "GET /static/results/dummy_session_id/output.png HTTP/1.1" 404 -
127.0.0.1 - - [29/Jul/2020 09:59:47] "GET /favicon.ico HTTP/1.1" 404 -
[2020-07-29 10:00:00,027] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/Users/anhdai/Downloads/EAST-master/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/anhdai/Downloads/EAST-master/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/anhdai/Downloads/EAST-master/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/anhdai/Downloads/EAST-master/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/anhdai/Downloads/EAST-master/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/anhdai/Downloads/EAST-master/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "run_demo_server.py", line 204, in index_post
    rst = get_predictor(checkpoint_path)(img)
  File "run_demo_server.py", line 39, in get_predictor
    import model
  File "/Users/anhdai/Downloads/EAST-master/model.py", line 4, in <module>
    from tensorflow.contrib import slim
ModuleNotFoundError: No module named 'tensorflow.contrib'
```

I have similar case when run server and submit photo.
