### ISSUE TITLE
An error about lanms

### ISSUE THREAD

**Issue by WhiteSouth** [argman/EAST#70]
When I run the demo ,I get the mistake that 
**" raise RuntimeError('Cannot compile lanms: {}'.format(BASE_DIR))
RuntimeError: Cannot compile lanms: /media/reborn/Others/Study/CD/EAST/lanms"**

And I don't know how to solve the problem ,could you give me some help?

**Comment by WhiteSouth** [comment]
And when I make in lamns,the problem is **g++: error: unrecognized command line option ‘-fno-plt’
Makefile:10: recipe for target 'adaptor.so' failed
make: *** [adaptor.so] Error 1**

**Comment by zxytim** [comment]
Please paste the output of `g++ --version`

**Comment by WhiteSouth** [comment]
It doesn't make;
**daptor.cpp include/clipper/clipper.cpp --shared -fPIC
g++: error: unrecognized command line option ‘-fno-plt’
Makefile:10: recipe for target 'adaptor.so' failed
make: *** [adaptor.so] Error 1**
the problem is above.If I changed the GCC from 5.4 to 4.8. The problem is still there...Can you give some help?

**Comment by lizzyYL** [comment]
Have you resolved this problem?And How? I have met this,too... Would you share the method with me ,thank you!(^_^)

**Comment by idoki** [comment]
It's a matter of compiling versions.
Until you get that right, you can comment out the lanms import and usage in merge_quadrangle_n9

**Comment by lizzyYL** [comment]
I have already resolve it, but thanks anyway~ and  you're right:)  I have update gcc from 5.4 to 6.0. That's the matter of compiler version.

**Comment by lfdeep** [comment]
hello! I meet the same problems,if I don't update gcc version,how i solve this problems?Could you give me any help?

**Comment by kfugosic** [comment]
Any instructions for windows? I tried mingw32-make, but it throws " fatal error: Python.h: No such file or directory" even if I include path to Python36/include.
I did what idoki suggested as workaround, but I would like to fix this.

**Comment by tsing-cv** [comment]
hello , i also met this problem, could you share your method ?

**Comment by RameshOswal** [comment]
Until you get that right, you can comment out the lanms import and usage in merge_quadrangle_n9

for me this worked

**Comment by santhoshav15** [comment]
I updated my `gcc` to `6`
upgraded `gcc` using https://gist.github.com/zuyu/7d5682a5c75282c596449758d21db5ed http://tuxamito.com/wiki/index.php/Installing_newer_GCC_versions_in_Ubuntu https://gist.github.com/application2000/73fd6f4bf1be6600a2cf9f56315a2d91
Unfortunately i had miniconda3 installed on my system which pointed to python 3.7
now i'm having this error being displayed

> 
> /home/lenavo/EAST/lanms
> make: Entering directory '/home/lenavo/EAST/lanms'
> make: 'adaptor.so' is up to date.
> make: Leaving directory '/home/lenavo/EAST/lanms'
> main
> loading model
> resnet_v1_50/block1 (?, ?, ?, 256)
> resnet_v1_50/block2 (?, ?, ?, 512)
> resnet_v1_50/block3 (?, ?, ?, 1024)
> resnet_v1_50/block4 (?, ?, ?, 2048)
> Shape of f_0 (?, ?, ?, 2048)
> Shape of f_1 (?, ?, ?, 512)
> Shape of f_2 (?, ?, ?, 256)
> Shape of f_3 (?, ?, ?, 64)
> Shape of h_0 (?, ?, ?, 2048), g_0 (?, ?, ?, 2048)
> Shape of h_1 (?, ?, ?, 128), g_1 (?, ?, ?, 128)
> Shape of h_2 (?, ?, ?, 64), g_2 (?, ?, ?, 64)
> Shape of h_3 (?, ?, ?, 32), g_3 (?, ?, ?, 32)
> 2018-12-12 13:23:57.411277: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> 32 text boxes before nms
> Traceback (most recent call last):
>   File "east.py", line 194, in <module>
>     main()
>   File "east.py", line 190, in main
>     predict((image_path))
>   File "east.py", line 164, in predict
>     rst = get_predictor(checkpoint_path)(img)
>   File "east.py", line 100, in predictor
>     boxes, timer = detect(score_map = score, geo_map=geometry, timer=timer)
>   File "/home/lenavo/EAST/eval.py", line 98, in detect
>     boxes = lanms.merge_quadrangle_n9(boxes.astype('float32'), nms_thres)
>   File "/home/lenavo/EAST/lanms/__init__.py", line 13, in merge_quadrangle_n9
>     from .adaptor import merge_quadrangle_n9 as nms_impl
> ImportError: Python version mismatch: module was compiled for version 3.7, while the interpreter is running version 3.5.
> 

Any idea, on how to solve this issue?

I tried

> I removed python 3.7
> Then reinstall gcc 6

Completely removed gcc
[sudo apt-get remove --auto-remove gcc ](https://www.howtoinstall.co/en/ubuntu/xenial/gcc?action=remove)

Reinstalled it again

But unable to solve the issue

**Comment by saharudra** [comment]
@santhoshav15 were you able to resolve this?

**Comment by liuzhuang1024** [comment]
were you able to resolve this?

**Comment by gdelab** [comment]
@IngleJaya95 I face the same issue, were you able to solve it ?

**Comment by jaya-ingle** [comment]
@gdelab No!

**Comment by gdelab** [comment]
Me neither, the best I could do was comment  `boxes = lanms.merge_quadrangle_n9(boxes.astype('float32'), nms_thres)` and uncomment 
`   boxes = nms_locality.nms_locality(boxes.astype(np.float64), nms_thres) ` in [ eval.py/detect](https://github.com/argman/EAST/blob/master/eval.py)

**Comment by dianeoyen** [comment]
> Me neither, the best I could do was comment `boxes = lanms.merge_quadrangle_n9(boxes.astype('float32'), nms_thres)` and uncomment
> ` boxes = nms_locality.nms_locality(boxes.astype(np.float64), nms_thres)` in [ eval.py/detect](https://github.com/argman/EAST/blob/master/eval.py)

Also, comment 'import lanms' line
