### ISSUE TITLE
Problems occurs  when run run_demo_server.py 

### ISSUE THREAD

**Issue by lizzyYL** [argman/EAST#84]
## I have downloaded the pre-trained model from baiduyun, and I only want to try the server.But when I runned run_demo_server.py, this problem occured. should I do something in icdar.py? Or must I download the icdar dataset? Or anything else? 
Please give me some suggestions.Thank you very much!

==========================================================
yangliu@AMAX:~/pythoncode/EAST-master$ python3 run_demo_server.py --checkpoint-path /home/yangliu/pythoncode/EAST-master/east_icdar2015_resnet_v1_50_rbox/
 * Running on http://0.0.0.0:8769/ (Press CTRL+C to quit)
127.0.0.1 - - [14/Dec/2017 09:33:24] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 09:33:24] "GET /static/css/app.css HTTP/1.1" 304 -
127.0.0.1 - - [14/Dec/2017 09:33:25] "GET /static/results/dummy_session_id/output.png HTTP/1.1" 404 -
[2017-12-14 09:33:39,349] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/home/yangliu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/yangliu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/yangliu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/yangliu/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/yangliu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/yangliu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "run_demo_server.py", line 204, in index_post
    rst = get_predictor(checkpoint_path)(img)
  File "run_demo_server.py", line 40, in get_predictor
    from icdar import restore_rectangle
  File "/home/yangliu/pythoncode/EAST-master/icdar.py", line 606
    print 'text file {} does not exists'.format(txt_fn)                                                                                                                                                    
                                       ^                                                                                                                                                                   
SyntaxError: invalid syntax

**Comment by argman** [comment]
its a python version problem, you may correct yourself

**Comment by lizzyYL** [comment]
Thank you~ my python version now is 3.6, so you means that I should use python3.5? or python2.7?

**Comment by dersar00** [comment]
@argman Which python v I should use??
